### ISSUE TITLE
[Database] Some string attributes contain redundant spaces

### ISSUE THREAD

**Issue by jeffu110616** [nccucsmember/iCourse#2]
As title,
Some string attributes contain redundant spaces ( e.g. course_name_ch )

**Comment by jeffu110616** [comment]
@biceneutron DB部份有辦法解決這個嗎?

**Comment by biceneutron** [comment]
@jeffu110616 ezpz

**Comment by biceneutron** [comment]
@jeffu110616 has fixed.

**Comment by jeffu110616** [comment]
Mission Completed.
