### ISSUE TITLE
 Need More Params for POST /course/search

### ISSUE THREAD

**Issue by wilson8507** [nccucsmember/iCourse#4]
- [x] limit 參數：回傳特定筆數資料 (eg. limit=10, 回傳十筆)
- [x] offset 參數：從 offset 筆數開始回傳資料 (eg. offest=0&limit=10, 從第0筆開始回傳十筆，回傳第0到9筆，offset=10&limit=10, 從第10筆開始回傳十筆，, 回傳第10到19筆)

**Comment by wilson8507** [comment]
@jeffu110616

**Comment by wilson8507** [comment]
@jeffu110616 我有改好ㄌ -> #6

**Comment by jeffu110616** [comment]
@wilson8507  咦 你說 limit跟offset嗎?

**Comment by wilson8507** [comment]
恩恩

**Comment by jeffu110616** [comment]
@wilson8507 Sorry, 我原本要今晚弄的 Orz

**Comment by wilson8507** [comment]
沒事xd 不過有用到fuzzy_search的跟單純用sql query的速度差蠻多的，看要不要優化fuzzy_search

**Comment by jeffu110616** [comment]
Okay 我再看看怎麼優化
